#!/bin/bash

printHelp () { \
  echo "Usage:"
  echo "- new : write a new article"
  echo "- rm : delete an article"
  echo "- edit : edit an article"
}

getTitle () { \
  echo -n "Enter the new article's name: "
  read -r title
  echo -n "Add a prefix (language, etc): "
  read -r prefix
  [ "$prefix" == "" ] || prefix="[$prefix-$(date +%Y/%m/%d)]"
  [ "$prefix" == "" ] && prefix="[$(date +%Y/%m/%d)]"
  echo ""
}

delete () { \
  read -r n
  let i=1
  for t in `ls data/articles`
  do
    articletitle=$t
    [ "$i" == "$n" ] && rm data/articles/$t && break
    let i=$i+1
  done

  let i=1
  for t in `cat data/titles`
  do
    ([ "$t" == "@@" ] || [ "$i" == "$n" ]) || echo -n "$t " >> data/titlestemp
    [ "$t" == "@@" ] && let i=$i+1 && \
      ([ "$i" == "$n" ] || echo -e "\n@@" >> data/titlestemp)
  done 
  rm data/titles
  mv data/titlestemp data/titles

  echo "Succesfully deleted $articletitle"
}

write_new () { \
  echo -e "\n@@\n$prefix $title" >> data/titles
  touch data/articles/$filename
  $EDITOR data/articles/$filename
  echo "Succesfully created file \"$filename\" for article \"$title\""
}

listFiles () { \
  echo "Choose an article: "
  let i=1
  echo -n "$i: "
  for t in `cat data/titles`
  do
    [ "$t" == "@@" ] || echo -n "$t "
    [ "$t" == "@@" ] && echo "" && let i=$i+1 && echo -n "$i: "
  done 
  echo ""
}

make_name () { \
  filename=`date +%Y%m%d-%H%M`
  echo "Do you want to name the article text file yourself?"
  read -p "This won't show anywhere on the website nor the URLS. " -n 1 -r
  echo    # (optional) move to a new line
  if [[ ! $REPLY =~ ^[Yy]$ ]]
  then
    for word in `echo $title | tr -dc '[:alnum:] '`
    do
      filename="$filename-$word"
    done
  else  
    echo -ne "Please enter a short filename: "
    read -r words
    words=$(echo $words | tr -dc '[:alnum:] ' | tr ' ' '-')
    filename="$filename-$words"
  fi
}

edit () { \
  listFiles
  read -r n
  let i=1
  for t in `ls data/articles`
  do
    [ "$i" == "$n" ] && $EDITOR data/articles/$t && break
    let i=$i+1
  done
  echo "Succesfully edited $t."
  echo "Note: title modification is a work in progress. Please edit it directly in data/titles."
}

case "$1" in
  new) getTitle && make_name && write_new ;;
  rm) listFiles && delete ;;
  edit) edit;;
  *) printHelp ;;
esac
